### ISSUE TITLE
Migrate master branch to main branch

### ISSUE THREAD

**Issue by ksuchak1990** [Urban-Analytics/dust#101]
At the end of last year, GitHub changed the default name for the central branch from `master` to `main` as part of a drive to increase openness and inclusivity. Whilst this means that any new repositories created since then will adopt this approach, all pre-existing repositories require a manual change.

GitHub has made this manual change pretty easy:
* Open the repository on GitHub, 
* Go to **Settings > Branches > Default branch** 
* Click on the edit pencil on the right-hand side of the default branch panel
* Rename the branch from `master` to `main`

Making this change will warn you that this will not automatically change the naming convention on contributors' local versions of the repository; local naming conventions should be updated using the folllowing commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
Thoughts @nickmalleson? I think that you are the only one who can make this change as the repository owner.

**Comment by nickmalleson** [comment]
Thanks @ksuchak1990, changing it is a good idea, I've just done that. @RobertClay & @patricia-ternes just so you are aware, the default branch in DUST is now called `main` rather than `master`. This may not affect your local copies as you mostly develop in your own branches anyway, but if you do want to rename your local master branch you need to run these three commands that Keiran mentions:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
