### ISSUE TITLE
Kill particles that are taking too long to complete

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/dust#25]
(Patricia I'm happy to look at this, but would be interested in your thoughts). 

When running large numbers of particles, you end up with a few that take ages to complete. E.g. see the screenshot. At the start of the DA window there were 16 python processes all running simultaneously, working their way through a population of 1000 particles.  However, after a few hours, most particles have finished but a few remain and take ages. Here you can see that there are only 4 processes remaining. This is because the other 996 particles finished hours ago, but these last four are still going. 

![Screenshot 2020-05-05 at 16 33 46](https://user-images.githubusercontent.com/6339379/81084758-36bdf200-8eee-11ea-873b-9e8aa4703120.png)

I'm not sure why this is happenning. It might be to do with loads of random collisions taking place, but maybe there's a bug. Either way, one way round this might be to keep track of how long the particles are taking to complete and if any take too long, say more 10* the mean runtime of the whole population then we kill the process and discard them...

**Comment by patricia-ternes** [comment]
I believe this is because, for some reason, two agents are in the same place. This fact is physically impossible, and leads to a problem in calculating the collision time. In this case the time for the next collision is zero or negative and the code is stuck in an infinite while statement.

I added an if statement in the get_collisionTable method to avoid an infinite loop. 

`try:
    tmin = min(collisionTable)
    tmin = tmin[0]
    if tmin <= 1.0e-10:
       tmin = 0.02`

Probably the collision that occurs between the particles involved in this problem will be treated incorrectly, but as this fact is very rare, this collision is not statistically relevant.

The updated code is in my branch (dev_PT).

**Comment by nickmalleson** [comment]
Thanks Patricia, I'll try again now that you've made that change.

I also have a temporary fix to stop any models whose step is taking too long, but this assumes that `model.step` does actually finish! FYI here's what I put in the `particle_filter_gcs.step_particle()` function temporarily (if we like this idea I can add a step time limit as an additional option)
```
for i in range(num_iter):
  start_time = datetime.datetime.now()
  model.step()
  duration = datetime.datetime.now() - start_time
  if duration.seconds > 10:
    print(f"\tModel {particle_num} step {i} took {duration}. Not stepping further.")
    break
```
