### ISSUE TITLE
Review inclusion of Patterns in ODD for StationSim_GCS

### ISSUE THREAD

**Issue by ksuchak1990** [Urban-Analytics/dust#72]
The [updated version of ODD](http://eprints.bournemouth.ac.uk/33918/1/7.pdf) that came out this year has introduced the term "Patterns" into the **Overview** section (the first subsection has been revised from **Purpose** to **Purpose and patterns**). The term here seems to draw on the idea of pattern-oriented modelling (which has come up once or twice in previous meetings). Is this something that should be included in this ODD? Or should I just stick with the [previous version](http://bio.uib.no/te/papers/Grimm_2010_The_ODD_protocol_.pdf) of ODD? Views @nickmalleson?

**Comment by nickmalleson** [comment]
I don’t think it matters. If it isn’t too difficult to include it then you could add something on patterns. This may be interesting in itself and something worth you thinking about, especially for validation. E.g. can you validate on aggregate density *and* individual traces? Validating at multiple scales is an interesting area in ABMs anyway. 

But alternatively if you said in your thesis “I’m using version x of ODD” (which doesn’t include patterns) I don’t think anyone would mind. The main purpose of ODD is so that models can be explained clearly and formally. In my view, if your ODD does that then it isn’t so important to stick rigidly to a particular version.
